# Generated by Django 4.2.10 on 2024-03-04 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category1',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category1',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category2',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category2',
            name='slug',
        ),
    ]
